# Generated by Django 4.2.3 on 2024-04-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='app.entrega'),
        ),
    ]
